apiVersion: infra.luminous3d.example/v1alpha1
kind: Prefix
metadata: { name: prefix-bad-cidr }
spec:
  cidr: "::1"
  site: { kind: Site, name: home-fishlake }
  vlan: { kind: Vlan, name: vlan-management }
